apiVersion: v1
kind: Service
metadata:
  name: traefik
  namespace: traefik

spec:
  type: LoadBalancer
  externalTrafficPolicy: Cluster
  loadBalancerIP: {{replace_me}}
  selector:
    app: traefik
  ports:
    - protocol: TCP
      name: http
      port: 80
      targetPort: http
    - protocol: TCP
      name: https
      port: 443
      targetPort: https
    - protocol: TCP
      name: tcp
      port: 8081

---
apiVersion: v1
kind: Service
metadata:
  name: traefik-dashboard
  namespace: traefik
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      name: admin
      port: 8080
  selector:
    app: traefik