apiVersion: v1
kind: ConfigMap
metadata:
  name: traefik-config
  namespace: traefik
data:
  traefik.toml: |
    [Global]
      checkNewVersion = false
      sendAnonymousUsage = true
    [log]
      level = "WARN"
      format = "json"
    [api]
      insecure = true
      dashboard = true
    [entryPoints]
      [entryPoints.http]
        address = ":8000"
      [entryPoints.https]
        address = ":4443"
    [providers]
      [providers.kubernetesCRD]
      [providers.kubernetesIngress]
        ingressClass = "traefik-cert-manager"
    [ping]