apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: tls-com-example-httpbin                               {{replace this line}}
  namespace: httpbin
spec:
  secretName: tls-com-example-httpbin                         {{replace this line}}
  commonName: httpbin.example.com                             {{replace this line}}
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  dnsNames:
  - httpbin.example.com                                       {{replace this line}}